//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iitrust.CRL_Publication.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrlEntity
    {
        public CrlEntity()
        {
            this.EventLog = new HashSet<EventLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime NextUpdate { get; set; }
        public string File { get; set; }
    
        public virtual MessageTask MessageTask { get; set; }
        public virtual ICollection<EventLog> EventLog { get; set; }
    }
}
