//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iitrust.CRL_Publication.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrlModelContainer : DbContext
    {
        public CrlModelContainer()
            : base("name=CrlModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CrlEntity> CrlEntities { get; set; }
        public virtual DbSet<MessageTask> MessageTasks { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
    }
}
