//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iitrust.CRL_Publication.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTask
    {
        public int Id { get; set; }
        public System.DateTime SendingTime { get; set; }
    
        public virtual CrlEntity CrlEntity { get; set; }
    }
}
